BATTERY_DRAIN_PER_CELL: float = 0.5
BATTERY_DRAIN_SCAN: float = 1.0
BATTERY_DRAIN_DELIVER: float = 1.0
BATTERY_LOW_THRESHOLD: float = 20.0
BATTERY_CRITICAL_THRESHOLD: float = 5.0
SCAN_RADIUS_DEFAULT: int = 3
DRONE_FOV: float = 60.0          # camera field of view in degrees
BASE_X: int = 0
BASE_Y: int = 0
BASE_Z: int = 0